language: python

env:
  global:
    - IMAGE_VERSION=2.1.0
    - COMMANDBOX_VERSION=3.8.0
  matrix:
    - BUILD_IMAGE_DOCKERFILE=Dockerfile BUILD_IMAGE_TAG=ortussolutions/commandbox
    - BUILD_IMAGE_DOCKERFILE=alpine/Dockerfile BUILD_IMAGE_TAG=ortussolutions/commandbox:alpine
    - BUILD_IMAGE_DOCKERFILE=engines/Dockerfile.Lucee4 BUILD_IMAGE_TAG=ortussolutions/commandbox:lucee45
    - BUILD_IMAGE_DOCKERFILE=engines/Dockerfile.Lucee5 BUILD_IMAGE_TAG=ortussolutions/commandbox:lucee5
    - BUILD_IMAGE_DOCKERFILE=engines/Dockerfile.Adobe2016 BUILD_IMAGE_TAG=ortussolutions/commandbox:adobe2016
    - BUILD_IMAGE_DOCKERFILE=engines/Dockerfile.Adobe2016-3 BUILD_IMAGE_TAG=ortussolutions/commandbox:adobe2016.0.3
    - BUILD_IMAGE_DOCKERFILE=engines/Dockerfile.Adobe11 BUILD_IMAGE_TAG=ortussolutions/commandbox:adobe11

services:
  - docker

script:
  - docker-compose -f docker-compose.test.yml up --build

deploy:
  skip_cleanup: true
  on:
    branch: 
      - master
      - development
  provider: script
  script: ./resources/publish.sh
