language: python

env:
  global:
    - IMAGE_VERSION=3.2.1
    - COMMANDBOX_VERSION=5.2.1

jobs:
  include:
    # Debian Builds
    - env: BUILD_IMAGE_DOCKERFILE=builds/Base.Dockerfile BASE_BUILD_FILE=builds/base/Dockerfile BUILD_IMAGE_TAG=ortussolutions/commandbox ARCH=x86_64
      os: linux
      arch: amd64
    - env: BUILD_IMAGE_DOCKERFILE=builds/Base.Dockerfile BASE_BUILD_FILE=builds/base/Dockerfile BUILD_IMAGE_TAG=ortussolutions/commandbox:arm64 ARCH=aarch64
      os: linux
      arch: arm64
    - env: BUILD_IMAGE_DOCKERFILE=builds/Base.Dockerfile BASE_BUILD_FILE=builds/base/JRE8.Dockerfile BUILD_IMAGE_TAG=ortussolutions/commandbox:jdk8 ARCH=x86_64
      os: linux
      arch: amd64
    - env: BUILD_IMAGE_DOCKERFILE=builds/Base.Dockerfile BASE_BUILD_FILE=builds/base/JRE8.Dockerfile BUILD_IMAGE_TAG=ortussolutions/commandbox:arm64-jdk8 ARCH=aarch64
      os: linux
      arch: arm64
    - env: BUILD_IMAGE_DOCKERFILE=builds/Lucee5.Dockerfile BASE_BUILD_FILE=builds/base/Dockerfile BUILD_IMAGE_TAG=ortussolutions/commandbox:lucee5 ARCH=x86_64
      os: linux
      arch: amd64
    - env: BUILD_IMAGE_DOCKERFILE=builds/Lucee5.Dockerfile BASE_BUILD_FILE=builds/base/Dockerfile BUILD_IMAGE_TAG=ortussolutions/commandbox:arm64-lucee5 ARCH=aarch64
      os: linux
      arch: arm64
    - env: BUILD_IMAGE_DOCKERFILE=builds/LuceeLight.Dockerfile BASE_BUILD_FILE=builds/base/Dockerfile BUILD_IMAGE_TAG=ortussolutions/commandbox:lucee-light ARCH=x86_64
      os: linux
      arch: amd64
    - env: BUILD_IMAGE_DOCKERFILE=builds/LuceeLight.Dockerfile BASE_BUILD_FILE=builds/base/Dockerfile BUILD_IMAGE_TAG=ortussolutions/commandbox:arm64-lucee-light ARCH=aarch64
      os: linux
      arch: arm64
    - env: BUILD_IMAGE_DOCKERFILE=builds/Adobe2016.Dockerfile BASE_BUILD_FILE=builds/base/JRE8.Dockerfile BUILD_IMAGE_TAG=ortussolutions/commandbox:adobe2016 ARCH=x86_64
      os: linux
      arch: amd64
    - env: BUILD_IMAGE_DOCKERFILE=builds/Adobe2016.Dockerfile BASE_BUILD_FILE=builds/base/JRE8.Dockerfile BUILD_IMAGE_TAG=ortussolutions/commandbox:arm64-adobe2016 ARCH=aarch64
      os: linux
      arch: arm64
    - env: BUILD_IMAGE_DOCKERFILE=builds/Adobe2018.Dockerfile BASE_BUILD_FILE=builds/base/Dockerfile BUILD_IMAGE_TAG=ortussolutions/commandbox:adobe2018 ARCH=x86_64
      os: linux
      arch: amd64
    - env: BUILD_IMAGE_DOCKERFILE=builds/Adobe2018.Dockerfile BASE_BUILD_FILE=builds/base/Dockerfile BUILD_IMAGE_TAG=ortussolutions/commandbox:arm64-adobe2018 ARCH=aarch64
      os: linux
      arch: arm64
    - env: BUILD_IMAGE_DOCKERFILE=builds/Adobe2021.Dockerfile BASE_BUILD_FILE=builds/base/Dockerfile BUILD_IMAGE_TAG=ortussolutions/commandbox:adobe2021 ARCH=x86_64
      os: linux
      arch: amd64
    - env: BUILD_IMAGE_DOCKERFILE=builds/Adobe2021.Dockerfile BASE_BUILD_FILE=builds/base/Dockerfile BUILD_IMAGE_TAG=ortussolutions/commandbox:arm64-adobe2021 ARCH=aarch64
      os: linux
      arch: arm

    # Alpine builds
    - env: BUILD_IMAGE_DOCKERFILE=builds/Base.Alpine.Dockerfile BASE_BUILD_FILE=builds/base/Alpine.Dockerfile BUILD_IMAGE_TAG=ortussolutions/commandbox:alpine ARCH=x86_64
      os: linux
      arch: amd64
    - env: BUILD_IMAGE_DOCKERFILE=builds/Base.Alpine.Dockerfile BASE_BUILD_FILE=builds/base/Alpine.Dockerfile BUILD_IMAGE_TAG=ortussolutions/commandbox:arm64-alpine ARCH=aarch64
      os: linux
      arch: arm64
    - env: BUILD_IMAGE_DOCKERFILE=builds/Base.Alpine.Dockerfile BASE_BUILD_FILE=builds/base/Alpine.JRE8.Dockerfile BUILD_IMAGE_TAG=ortussolutions/commandbox:jdk8-alpine ARCH=x86_64
      os: linux
      arch: amd64
    - env: BUILD_IMAGE_DOCKERFILE=builds/Base.Alpine.Dockerfile BASE_BUILD_FILE=builds/base/Alpine.JRE8.Dockerfile BUILD_IMAGE_TAG=ortussolutions/commandbox:jdk8-alpine ARCH=aarch64
      os: linux
      arch: arm64
    - env: BUILD_IMAGE_DOCKERFILE=builds/Lucee5.Dockerfile BASE_BUILD_FILE=builds/base/Alpine.Dockerfile BUILD_IMAGE_TAG=ortussolutions/commandbox:lucee5-alpine ARCH=x86_64
      os: linux
      arch: amd64
    - env: BUILD_IMAGE_DOCKERFILE=builds/Lucee5.Dockerfile BASE_BUILD_FILE=builds/base/Alpine.Dockerfile BUILD_IMAGE_TAG=ortussolutions/commandbox:lucee5-alpine ARCH=aarch64
      os: linux
      arch: arm64
    - env: BUILD_IMAGE_DOCKERFILE=builds/LuceeLight.Dockerfile BASE_BUILD_FILE=builds/base/Alpine.Dockerfile BUILD_IMAGE_TAG=ortussolutions/commandbox:lucee-light-alpine ARCH=x86_64
      os: linux
      arch: amd64
    - env: BUILD_IMAGE_DOCKERFILE=builds/LuceeLight.Dockerfile BASE_BUILD_FILE=builds/base/Alpine.Dockerfile BUILD_IMAGE_TAG=ortussolutions/commandbox:lucee-light-alpine ARCH=aarch64
      os: linux
      arch: arm64
    - env: BUILD_IMAGE_DOCKERFILE=builds/Adobe2016.Dockerfile BASE_BUILD_FILE=builds/base/Alpine.JRE8.Dockerfile BUILD_IMAGE_TAG=ortussolutions/commandbox:adobe2016-alpine ARCH=x86_64
      os: linux
      arch: amd64
    - env: BUILD_IMAGE_DOCKERFILE=builds/Adobe2016.Dockerfile BASE_BUILD_FILE=builds/base/Alpine.JRE8.Dockerfile BUILD_IMAGE_TAG=ortussolutions/commandbox:adobe2016-alpine ARCH=aarch64
      os: linux
      arch: arm64
    - env: BUILD_IMAGE_DOCKERFILE=builds/Adobe2018.Dockerfile BASE_BUILD_FILE=builds/base/Alpine.Dockerfile BUILD_IMAGE_TAG=ortussolutions/commandbox:adobe2018-alpine ARCH=x86_64
      os: linux
      arch: amd64
    - env: BUILD_IMAGE_DOCKERFILE=builds/Adobe2018.Dockerfile BASE_BUILD_FILE=builds/base/Alpine.Dockerfile BUILD_IMAGE_TAG=ortussolutions/commandbox:adobe2018-alpine ARCH=aarch64
      os: linux
      arch: arm64
    - env: BUILD_IMAGE_DOCKERFILE=builds/Adobe2021.Dockerfile BASE_BUILD_FILE=builds/base/Alpine.Dockerfile BUILD_IMAGE_TAG=ortussolutions/commandbox:adobe2021-alpine ARCH=x86_64
      os: linux
      arch: amd64
    - env: BUILD_IMAGE_DOCKERFILE=builds/Adobe2021.Dockerfile BASE_BUILD_FILE=builds/base/Alpine.Dockerfile BUILD_IMAGE_TAG=ortussolutions/commandbox:adobe2021-alpine ARCH=aarch64
      os: linux
      arch: arm64

  
    
services:
  - docker

script:
  # update our version numbers before building
  - find ./builds/base -type f -exec sed -i '' -e "s/@version@/${IMAGE_VERSION}/g" {} \;
  - docker build --no-cache --build-arg COMMANDBOX_VERSION=$COMMANDBOX_VERSION --build-arg VERSION=$IMAGE_VERSION --build-arg ARCH=$ARCH -t commandbox-base -f ./$BASE_BUILD_FILE $TRAVIS_BUILD_DIR/
  - docker-compose -f docker-compose.test.yml up --build --exit-code-from sut
  - docker-compose -f docker-compose.secret-test.yml up --build --exit-code-from sut

deploy:
  - provider : script
    skip_cleanup: true
    on:
      all_branches: true
      condition: "$TRAVIS_BRANCH = $TRAVIS_TAG"
    script: ./resources/publish.sh
  - provider: script
    skip_cleanup: true
    on:
      tags : false
      branch: 
        - master
        - development
    script: ./resources/publish.sh
