language: python

env:
  global:
    - IMAGE_VERSION=2.1.1
    - COMMANDBOX_VERSION=3.9.0
  matrix:
    - BUILD_IMAGE_DOCKERFILE=Dockerfile BUILD_IMAGE_TAG=ortussolutions/commandbox
    - BUILD_IMAGE_DOCKERFILE=alpine/Dockerfile BUILD_IMAGE_TAG=ortussolutions/commandbox:alpine
    - BUILD_IMAGE_DOCKERFILE=engines/Dockerfile.Lucee4 BUILD_IMAGE_TAG=ortussolutions/commandbox:lucee45
    - BUILD_IMAGE_DOCKERFILE=engines/Dockerfile.Lucee5 BUILD_IMAGE_TAG=ortussolutions/commandbox:lucee5
    - BUILD_IMAGE_DOCKERFILE=engines/Dockerfile.Adobe2016 BUILD_IMAGE_TAG=ortussolutions/commandbox:adobe2016
    - BUILD_IMAGE_DOCKERFILE=engines/Dockerfile.Adobe2016-3 BUILD_IMAGE_TAG=ortussolutions/commandbox:adobe2016.0.3
    - BUILD_IMAGE_DOCKERFILE=engines/Dockerfile.Adobe11 BUILD_IMAGE_TAG=ortussolutions/commandbox:adobe11

matrix:
  allow_failures:
    - env: TRAVIS_BRANCH=development BUILD_IMAGE_DOCKERFILE=alpine/Dockerfile
    - env: TRAVIS_BRANCH=development BUILD_IMAGE_DOCKERFILE=alpine/Dockerfile.Lucee4
    - env: TRAVIS_BRANCH=development BUILD_IMAGE_DOCKERFILE=alpine/Dockerfile.Lucee5
    - env: TRAVIS_BRANCH=development BUILD_IMAGE_DOCKERFILE=alpine/Dockerfile.Adobe2016
    - env: TRAVIS_BRANCH=development BUILD_IMAGE_DOCKERFILE=alpine/Dockerfile.Adobe2016-3
    - env: TRAVIS_BRANCH=development BUILD_IMAGE_DOCKERFILE=alpine/Dockerfile.Adobe11

services:
  - docker

script:
  - docker-compose -f docker-compose.test.yml up --build --exit-code-from sut
  - docker-compose -f docker-compose.secret-test.yml up --build --exit-code-from sut

deploy:
  skip_cleanup: true
  on:
    branch: 
      - master
      - development
  provider: script
  script: ./resources/publish.sh
