language: python

env:
  global:
    - IMAGE_VERSION=2.5.0
    - COMMANDBOX_VERSION=4.5.0
  matrix:
    # Debian Builds
    - BUILD_IMAGE_DOCKERFILE=builds/Base.Dockerfile BASE_BUILD_FILE=builds/base/Dockerfile BUILD_IMAGE_TAG=ortussolutions/commandbox
    - BUILD_IMAGE_DOCKERFILE=builds/Lucee4.Dockerfile BASE_BUILD_FILE=builds/base/Dockerfile BUILD_IMAGE_TAG=ortussolutions/commandbox:lucee45
    - BUILD_IMAGE_DOCKERFILE=builds/Lucee5.Dockerfile BASE_BUILD_FILE=builds/base/Dockerfile BUILD_IMAGE_TAG=ortussolutions/commandbox:lucee5
    - BUILD_IMAGE_DOCKERFILE=builds/Adobe11.Dockerfile BASE_BUILD_FILE=builds/base/Dockerfile BUILD_IMAGE_TAG=ortussolutions/commandbox:adobe11
    - BUILD_IMAGE_DOCKERFILE=builds/Adobe2016.Dockerfile BASE_BUILD_FILE=builds/base/Dockerfile BUILD_IMAGE_TAG=ortussolutions/commandbox:adobe2016
    - BUILD_IMAGE_DOCKERFILE=builds/Adobe2018.Dockerfile BASE_BUILD_FILE=builds/base/JRE.11Dockerfile BUILD_IMAGE_TAG=ortussolutions/commandbox:adobe2018
    # Alpine builds
    - BUILD_IMAGE_DOCKERFILE=builds/Base.Alpine.Dockerfile BASE_BUILD_FILE=builds/base/Alpine.Dockerfile BUILD_IMAGE_TAG=ortussolutions/commandbox:alpine
    - BUILD_IMAGE_DOCKERFILE=builds/Lucee4.Dockerfile BASE_BUILD_FILE=builds/base/Alpine.Dockerfile BUILD_IMAGE_TAG=ortussolutions/commandbox:lucee45-alpine
    - BUILD_IMAGE_DOCKERFILE=builds/Lucee5.Dockerfile BASE_BUILD_FILE=builds/base/Alpine.Dockerfile BUILD_IMAGE_TAG=ortussolutions/commandbox:lucee5-alpine
    - BUILD_IMAGE_DOCKERFILE=builds/Adobe11.Dockerfile BASE_BUILD_FILE=builds/base/Alpine.Dockerfile BUILD_IMAGE_TAG=ortussolutions/commandbox:adobe11-alpine
    - BUILD_IMAGE_DOCKERFILE=builds/Adobe2016.Dockerfile BASE_BUILD_FILE=builds/base/Alpine.Dockerfile BUILD_IMAGE_TAG=ortussolutions/commandbox:adobe2016-alpine
    - BUILD_IMAGE_DOCKERFILE=builds/Adobe2018.Dockerfile BASE_BUILD_FILE=builds/base/Alpine.JRE11.Dockerfile BUILD_IMAGE_TAG=ortussolutions/commandbox:adobe2018-alpine

services:
  - docker

script:
  - docker build --no-cache --build-arg COMMANDBOX_VERSION=$COMMANDBOX_VERSION -t commandbox-base -f ./$BASE_BUILD_FILE $TRAVIS_BUILD_DIR/
  - docker-compose -f docker-compose.test.yml up --build --exit-code-from sut
  - docker-compose -f docker-compose.secret-test.yml up --build --exit-code-from sut

deploy:
  skip_cleanup: true
  on:
    branch: 
      - master
      - development
  provider: script
  script: ./resources/publish.sh
