version: '2.1'

services:

  test:
    image: ortussolutions/commandbox
    environment:
      cfconfig_adminPassword: testing
    volumes:
      - ./test:/srv/app
      - ./build:/opt/build:ro
    ports:
      - "8080:8080"