version: '3.1'

# This tests the CommandBox Docker Secrets implementation
# To test:
# BUILD_IMAGE_DOCKERFILE=Dockerfile BUILD_IMAGE_TAG=ortussolutions/commandbox docker-compose -f docker-compose.secret-test.yml up --build

services:

  sut:
    build:
      context: .
      dockerfile: "./${BUILD_IMAGE_DOCKERFILE}"
      args :
        - COMMANDBOX_VERSION
    container_name: secret-test
    environment:
      - SOME_VAR=foo
      - TEST_DOCKER_SECRET=<<SECRET:test_docker_secret>>
      - BOX_SERVER_CFCONFIGFILE=myConfigs.json
      - IMAGE_TESTING_IN_PROGRESS=true
    volumes: 
      - ./test:/app
      - ./build/tests/myConfigs.json:./app/myConfigs.json
      - ./build:/usr/local/lib/build
    secrets:
      - test_docker_secret
    command: /usr/local/lib/build/tests/test.secrets.sh

secrets:
  test_docker_secret:
    file: ./build/tests/secrets/test_docker_secret