version: '3.1'

# This tests the CommandBox Docker Secrets implementation
# To test:
# BUILD_IMAGE_DOCKERFILE=Dockerfile BUILD_IMAGE_TAG=ortussolutions/commandbox docker-compose -f docker-compose.secret-test.yml up --build
# The proof is that the admin (http://localhost:8080/lucee/admin/web.cfm) will have the password secretvalue, which comes from the test_docker_secret Docker secret.

services:

  sut:
    build:
      context: .
      dockerfile: "./${BUILD_IMAGE_DOCKERFILE}"
    container_name: secret-test
    environment:
      #- ENV_SECRETS_DEBUG # uncomment to emit output during secret replacement
      - SOME_VAR=foo
      - TEST_DOCKER_SECRET={{DOCKER-SECRET:test_docker_secret}}
      - CFCONFIG=/build/tests/myConfigs.json
      - IMAGE_TESTING_IN_PROGRESS=true
    volumes: 
      - ./test:/app
      - ./build:/root/build
    secrets:
      - test_docker_secret
    command: /root/build/tests/test.secrets.sh

secrets:
  test_docker_secret:
    file: ./build/tests/secrets/test_docker_secret